#---------------------------- Metadata Information ----------------------------#

# Site Name
name: BOJIT

# Site Author
author: James Bennion-Pedley

# Hosting URL
url: https://bojit.dev

# Git Remote: git@github.com:BOJIT/BOJIT.github.io.git

# Base URL (used when hosting the website in a subdirectory)
baseurl: ""

# File URL (for external assets)
fileurl: https://cdn.bojit.dev/files

# Image URL (for external assets)
imgurl: https://cdn.bojit.dev/img

# Page Generic URL format
permalink: /:categories/:title/

# Website Version
version: v0.0.1

# Supported Categories
# - tutorials
# - projects
# - ramblings
# - galleries
# - experiments
# - [unlisted]

#------------------------- Links to social media pages ------------------------#
socials:
  youtube:
    url: https://www.youtube.com/channel/UCR7zc0TblvkjPy9DhAWUkvA
    logo: fa-youtube-play
  linkedin:
    url: https://www.linkedin.com/in/james-bennion-pedley-bab14a146/
    logo: fa-linkedin
  github:
    url: https://github.com/BOJIT
    logo: fa-github
  facebook:
    url: https://www.facebook.com/James.BOJIT
    logo: fa-facebook
  soundloud:
    url: https://soundcloud.com/james-bojit
    logo: fa-soundcloud

#---------------------------- Service Definitions -----------------------------#

# Add Disqus footer to select pages
disqus: BOJIT-blog

# Add Google Analytics
google_analytics: UA-141105755-1

#---------------------------- Jekyll Configuration ----------------------------#

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - TODO
  - .gitignore
